[package]
name = "cc-ex"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.4.1"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
axum="0.8.7"
tokio = { version = "1", features = ["full"] }